var http = require('http');

module.exports = function(cb) {
  var server = http.createServer(function(req, res) {
    res.writeHead(200, {'Content-Type': 'application/x-web-app-manifest+json'});
    res.end(JSON.stringify({
      "name":"Test App (deltron3030)",
      "description":"This app has been automatically generated by testmanifest.com",
      "version":new Date().getTime(),
      "icons":{
        "16":"http://testmanifest.com/icon-16.png",
        "48":"http://testmanifest.com/icon-48.png",
        "128":"http://testmanifest.com/icon-128.png"
      },
      "installs_allowed_from":[
        "*"
      ],
      "developer":{
        "name":"Gregory Koberger",
        "url":"http://gkoberger.net"
      }
    }));
  });
  server.listen(0, '0.0.0.0', function(err, a, b) {
    console.log('server.listen', err, a, b);
    console.log(server.address());
    cb(null, server);
  });
};